### ISSUE TITLE
تبدیل به پکیج

### ISSUE THREAD

**Issue by yekta-kalantary** [mojtabaRKS/laravel-persian-validation#10]
سلام
مد نظرت هست اینو تبدیل به پیکیج کنی براش vendor pubish بذاری؟
یا همین اوکیه؟

**Comment by mojtabaRKS** [comment]
> سلام مد نظرت هست اینو تبدیل به پیکیج کنی براش vendor pubish بذاری؟ یا همین اوکیه؟

salam yekta jan.... be nazaram age package nabashe behtare chon momkene harki ye tike az in code haro bardare ya shayad hamasho nakhad estefade kone...
nazare khodet chie?
